export const GROUND_LIST_REQUEST = "GROUND_LIST_REQUEST";
export const GROUND_LIST_SUCCESS = "GROUND_LIST_SUCCESS";
export const GROUND_LIST_FAIL = "GROUND_LIST_FAIL";

export const GROUND_DETAILS_REQUEST = "GROUND_DETAILS_REQUEST";
export const GROUND_DETAILS_SUCCESS = "GROUND_DETAILS_SUCCESS";
export const GROUND_DETAILS_FAIL = "GROUND_DETAILS_FAIL";

export const USER_GROUND_DETAILS_REQUEST = "USER_GROUND_DETAILS_REQUEST";
export const USER_GROUND_DETAILS_SUCCESS = "USER_GROUND_DETAILS_SUCCESS";
export const USER_GROUND_DETAILS_FAIL = "USER_GROUND_DETAILS_FAIL";
export const USER_GROUND_DETAILS_RESET = "USER_GROUND_DETAILS_RESET";

export const POST_GROUND_REQUEST = "POST_GROUND_REQUEST";
export const POST_GROUND_SUCCESS = "POST_GROUND_SUCCESS";
export const POST_GROUND_FAIL = "POST_GROUND_FAIL";

export const GROUND_LIST_REQUEST_TEST = "GROUND_LIST_REQUEST_TEST";
export const GROUND_LIST_SUCCESS_TEST = "GROUND_LIST_SUCCESS_TEST";
export const GROUND_LIST_FAIL_TEST = "GROUND_LIST_FAIL_TEST";

export const GROUND_CATEGORY_LIST_REQUEST = "GROUND_CATEGORY_LIST_REQUEST";
export const GROUND_CATEGORY_LIST_SUCCESS = "GROUND_CATEGORY_LIST_SUCCESS";
export const GROUND_CATEGORY_LIST_FAIL = "GROUND_CATEGORY_LIST_FAIL";
