export const GROUND_LIST_REQUEST = "GROUND_LIST_REQUEST";
export const GROUND_LIST_SUCCESS = "GROUND_LIST_SUCCESS";
export const GROUND_LIST_FAIL = "GROUND_LIST_FAIL";

export const GROUND_DETAILS_REQUEST = "GROUND_DETAILS_REQUEST";
export const GROUND_DETAILS_SUCCESS = "GROUND_DETAILS_SUCCESS";
export const GROUND_DETAILS_FAIL = "GROUND_DETAILS_FAIL";

export const USER_GROUND_DETAILS_REQUEST = "USER_GROUND_DETAILS_REQUEST";
export const USER_GROUND_DETAILS_SUCCESS = "USER_GROUND_DETAILS_SUCCESS";
export const USER_GROUND_DETAILS_FAIL = "USER_GROUND_DETAILS_FAIL";
export const USER_GROUND_DETAILS_RESET = "USER_GROUND_DETAILS_RESET";

export const POST_GROUND_REQUEST = "POST_GROUND_REQUEST";
export const POST_GROUND_SUCCESS = "POST_GROUND_SUCCESS";
export const POST_GROUND_FAIL = "POST_GROUND_FAIL";

export const GROUND_LIST_REQUEST_TEST = "GROUND_LIST_REQUEST_TEST";
export const GROUND_LIST_SUCCESS_TEST = "GROUND_LIST_SUCCESS_TEST";
export const GROUND_LIST_FAIL_TEST = "GROUND_LIST_FAIL_TEST";

export const GROUND_CATEGORY_LIST_REQUEST = "GROUND_CATEGORY_LIST_REQUEST";
export const GROUND_CATEGORY_LIST_SUCCESS = "GROUND_CATEGORY_LIST_SUCCESS";
export const GROUND_CATEGORY_LIST_FAIL = "GROUND_CATEGORY_LIST_FAIL";

export const BROWSE_GROUND_LIST_REQUEST = "BROWSE_GROUND_LIST_REQUEST";
export const BROWSE_GROUND_LIST_SUCCESS = "BROWSE_GROUND_LIST_SUCCESS";
export const BROWSE_GROUND_LIST_FAIL = "BROWSE_GROUND_LIST_FAIL";

export const BROWSE_GROUND_UPDATE_REQUEST = "BROWSE_GROUND_UPDATE_REQUEST";
export const BROWSE_GROUND_UPDATE_SUCCESS = "BROWSE_GROUND_UPDATE_SUCCESS";
export const BROWSE_GROUND_UPDATE_FAIL = "BROWSE_GROUND_UPDATE_FAIL";

export const INSTOCKGROUND_UPDATE_REQUEST = "INSTOCKGROUND_UPDATE_REQUEST";
export const INSTOCKGROUND_UPDATE_SUCCESS = "INSTOCKGROUND_UPDATE_SUCCESS";
export const INSTOCKGROUND_UPDATE_FAIL = "INSTOCKGROUND_UPDATE_FAIL";

export const GROUND_UPDATE_REQUEST = "GROUND_UPDATE_REQUEST";
export const GROUND_UPDATE_SUCCESS = "GROUND_UPDATE_SUCCESS";
export const GROUND_UPDATE_FAIL = "GROUND_UPDATE_FAIL";

export const GROUND_DELETE_REQUEST = "GROUND_DELETE_REQUEST";
export const GROUND_DELETE_SUCCESS = "GROUND_DELETE_SUCCESS";
export const GROUND_DELETE_FAIL = "GROUND_DELETE_FAIL";

export const SELLER_GROUND_LIST_REQUEST = "SELLER_GROUND_LIST_REQUEST";
export const SELLER_GROUND_LIST_SUCCESS = "SELLER_GROUND_LIST_SUCCESS";
export const SELLER_GROUND_LIST_FAIL = "SELLER_GROUND_LIST_FAIL";

export const SELLER_GROUND_LIST_SOLD_REQUEST =
  "SELLER_GROUND_SOLD_LIST_REQUEST";
export const SELLER_GROUND_LIST_SOLD_SUCCESS =
  "SELLER_GROUND_SOLD_LIST_SUCCESS";
export const SELLER_GROUND_LIST_SOLD_FAIL = "SELLER_GROUND_SOLD_LIST_FAIL";

export const ASSIGNMENT_GROUND_REQUEST = "ASSIGNMENT_GROUND_REQUEST";
export const ASSIGNMENT_GROUND_SUCCEESS = "ASSIGNMENT_GROUND_SUCCESS";
export const ASSIGNMENT_GROUND_FAIL = "ASSIGNMENT_GROUND_FAIL";
