export const POST_HISTORY_REQUEST = "POST_HISTORY_REQUEST";
export const POST_HISTORY_SUCCESS = "POST_HISTORY_SUCCESS";
export const POST_HISTORY_FAIL = "POST_HISTORY_FAIL";

export const POST_HISTORY_DELETE_REQUEST = "POST_HISTORY_DELETE_REQUEST";
export const POST_HISTORY_DELETE_SUCCESS = "POST_HISTORY_DELETE_SUCCESS";
export const POST_HISTORY_DELETE_FAIL = "POST_HISTORY_DELETE_FAIL";

export const POST_HISTORY_UPDATE_REQUEST = "POST_HISTORY_UPDATE_REQUEST";
export const POST_HISTORY_UPDATE_SUCCESS = "POST_HISTORY_UPDATE_SUCCESS";
export const POST_HISTORY_UPDATE_FAIL = "POST_HISTORY_UPDATE_FAIL";

export const POSTGROUND_HISTORY_REQUEST = "POSTGROUND_HISTORY_REQUEST";
export const POSTGROUND_HISTORY_SUCCESS = "POSTGROUND_HISTORY_SUCCESS";
export const POSTGROUND_HISTORY_FAIL = "POSTGROUND_HISTORY_FAIL";

export const POSTGROUND_HISTORY_DELETE_REQUEST =
  "POSTGROUND_HISTORY_DELETE_REQUEST";
export const POSTGROUND_HISTORY_DELETE_SUCCESS =
  "POSTGROUND_HISTORY_DELETE_SUCCESS";
export const POSTGROUND_HISTORY_DELETE_FAIL = "POSTGROUND_HISTORY_DELETE_FAIL";

export const POSTGROUND_HISTORY_UPDATE_REQUEST =
  "POSTGROUND_HISTORY_UPDATE_REQUEST";
export const POSTGROUND_HISTORY_UPDATE_SUCCESS =
  "POSTGROUND_HISTORY_UPDATE_SUCCESS";
export const POSTGROUND_HISTORY_UPDATE_FAIL = "POSTGROUND_HISTORY_UPDATE_FAIL";
