export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const USER_PRODUCT_DETAILS_REQUEST = "USER_PRODUCT_DETAILS_REQUEST";
export const USER_PRODUCT_DETAILS_SUCCESS = "USER_PRODUCT_DETAILS_SUCCESS";
export const USER_PRODUCT_DETAILS_FAIL = "USER_PRODUCT_DETAILS_FAIL";
export const USER_PRODUCT_DETAILS_RESET = "USER_PRODUCT_DETAILS_RESET";

export const POST_PRODUCT_REQUEST = "POST_PRODUCT_REQUEST";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_FAIL = "POST_PRODUCT_FAIL";
