export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const USER_PRODUCT_DETAILS_REQUEST = "USER_PRODUCT_DETAILS_REQUEST";
export const USER_PRODUCT_DETAILS_SUCCESS = "USER_PRODUCT_DETAILS_SUCCESS";
export const USER_PRODUCT_DETAILS_FAIL = "USER_PRODUCT_DETAILS_FAIL";
export const USER_PRODUCT_DETAILS_RESET = "USER_PRODUCT_DETAILS_RESET";

export const POST_PRODUCT_REQUEST = "POST_PRODUCT_REQUEST";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_FAIL = "POST_PRODUCT_FAIL";

export const PRODUCT_LIST_REQUEST_TEST = "PRODUCT_LIST_REQUEST_TEST";
export const PRODUCT_LIST_SUCCESS_TEST = "PRODUCT_LIST_SUCCESS_TEST";
export const PRODUCT_LIST_FAIL_TEST = "PRODUCT_LIST_FAIL_TEST";

export const PRODUCT_CATEGORY_LIST_REQUEST = "PRODUCT_CATEGORY_LIST_REQUEST";
export const PRODUCT_CATEGORY_LIST_SUCCESS = "PRODUCT_CATEGORY_LIST_SUCCESS";
export const PRODUCT_CATEGORY_LIST_FAIL = "PRODUCT_CATEGORY_LIST_FAIL";

export const BROWSE_LIST_REQUEST = "BROWSE_LIST_REQUEST";
export const BROWSE_LIST_SUCCESS = "BROWSE_LIST_SUCCESS";
export const BROWSE_LIST_FAIL = "BROWSE_LIST_FAIL";

export const BROWSE_UPDATE_REQUEST = "BROWSE_UPDATE_REQUEST";
export const BROWSE_UPDATE_SUCCESS = "BROWSE_UPDATE_SUCCESS";
export const BROWSE_UPDATE_FAIL = "BROWSE_UPDATE_FAIL";

export const SELLER_PRODUCT_LIST_REQUEST = "SELLER_PRODUCT_LIST_REQUEST";
export const SELLER_PRODUCT_LIST_SUCCESS = "SELLER_PRODUCT_LIST_SUCCESS";
export const SELLER_PRODUCT_LIST_FAIL = "SELLER_PRODUCT_LIST_FAIL";

export const SELLER_PRODUCT_LIST_SOLD_REQUEST =
  "SELLER_PRODUCT_SOLD_LIST_REQUEST";
export const SELLER_PRODUCT_LIST_SOLD_SUCCESS =
  "SELLER_PRODUCT_SOLD_LIST_SUCCESS";
export const SELLER_PRODUCT_LIST_SOLD_FAIL = "SELLER_PRODUCT_SOLD_LIST_FAIL";

export const INSTOCK_UPDATE_REQUEST = "INSTOCK_UPDATE_REQUEST";
export const INSTOCK_UPDATE_SUCCESS = "INSTOCK_UPDATE_SUCCESS";
export const INSTOCK_UPDATE_FAIL = "INSTOCK_UPDATE_FAIL";

export const ASSIGNMENT_REQUEST = "ASSIGNMENT_REQUEST";
export const ASSIGNMENT_SUCCEESS = "ASSIGNMENT_SUCCESS";
export const ASSIGNMENT_FAIL = "ASSIGNMENT_FAIL";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_ADMIN_LIST_REQUEST = "PRODUCT_ADMIN_LIST_REQUEST";
export const PRODUCT_ADMIN_LIST_SUCCESS = "PRODUCT_ADMIN_LIST_SUCCESS";
export const PRODUCT_ADMIN_LIST_FAIL = "PRODUCT_ADMIN_LIST_FAIL";
