export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_TOPSELLERS_LIST_REQUEST = "USER_TOPSELLERS_LIST_REQUEST";
export const USER_TOPSELLERS_LIST_SUCCESS = "USER_TOPSELLERS_LIST_SUCCESS";
export const USER_TOPSELLERS_LIST_FAIL = "USER_TOPSELLERS_LIST_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";

export const USER_ADDRESS_MAP_CONFIRM = "USER_ADDRESS_MAP_CONFIRM";

export const SELLER_LIST_REQUEST = "SELLER_LIST_REQUEST";
export const SELLER_LIST_SUCCESS = "SELLER_LIST_SUCCESS";
export const SELLER_LIST_FAIL = "SELLER_LIST_FAIL";

export const SELLER_CREATE_REQUEST = "SELLER_CREATE_REQUEST";
export const SELLER_CREATE_SUCCESS = "SELLER_CREATE_SUCCESS";
export const SELLER_CREATE_FAIL = "SELLER_CREATE_FAIL";

export const SELLER_UPDATE_REQUEST = "SELLER_UPDATE_REQUEST";
export const SELLER_UPDATE_SUCCESS = "SELLER_UPDATE_SUCCESS";
export const SELLER_UPDATE_FAIL = "SELLER_UPDATE_FAIL";

export const SELLER_DELETE_REQUEST = "SELLER_DELETE_REQUEST";
export const SELLER_DELETE_SUCCESS = "SELLER_DELETE_SUCCESS";
export const SELLER_DELETE_FAIL = "SELLER_DELETE_FAIL";

export const SELLER_SALARY_REQUEST = "SELLER_SALARY_REQUEST";
export const SELLER_SALARY_SUCCESS = "SELLER_SALARY_SUCCESS";
export const SELLER_SALARY_FAIL = "SELLER_SALARY_FAIL";

export const SELLER_DETAILS_REQUEST = "SELLER_DETAILS_REQUEST";
export const SELLER_DETAILS_SUCCESS = "SELLER_DETAILS_SUCCESS";
export const SELLER_DETAILS_FAIL = "SELLER_DETAILS_FAIL";

export const SELLER_PAYMENT_SALARY_REQUEST = "SELLER_PAYMENT_SALARY_REQUEST";
export const SELLER_PAYMENT_SALARY_SUCCESS = "SELLER_PAYMENT_SALARY_SUCCESS";
export const SELLER_PAYMENT_SALARY_FAIL = "SELLER_PAYMENT_SALARY_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
