const data = {
  products: [
    {
      _id: '1',
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p1.jpg",
      price: 23,
      countInStock: 10,
      brand: "nike",
      rating: 2.5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: '2',
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 12,
      countInStock: 0,

      brand: "nike",
      rating: 1.5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: '3',
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 32,
      countInStock: 10,
      brand: "nike",
      rating: 3.5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: '4',
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p1.jpg",
      brand: "nike",
      price: 10130,
      countInStock: 10,
      rating: 4,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: '5',
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p1.jpg",
      price: 123,
      countInStock: 10,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: '6',
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 1010,
      countInStock: 10,
      brand: "nike",
      rating: 5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: '7',
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p1.jpg",
      price: 123,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality product",
    },
    {
      _id: '8',
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/p3.jpg",
      price: 123,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality product",
    },
  ],
};
export default data;
