Post http://localhost:5000/api/users/signin
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"loc123"
}

###
Post http://localhost:5000/api/users/register
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"loc123",
    "phone":"0981074090",
    "address":"đức chánh",
    "name":"Nguyễn Hữu Lộc"
}
###
Post  http://localhost:5000/api/users/info
Content-Type: application/json

{
    "id":"6200933a189dbf4d5f3020b7"
   
}
### get user
Get  http://localhost:5000/api/users/625ff142dfbfaa9c90bee899

### get seller
Get  http://localhost:5000/api/users/admin/seller

### get user
Get  http://localhost:5000/api/users/admin/user


### update user
Put  http://localhost:5000/api/users/admin/update
Content-Type: application/json

{
    "name":"Loc"
}